CPPC = g++
CFLAGS = -Wall

all:
	$(CPPC) $(CFLAGS) -o main Cuaternion.cpp

matmult: matmult.c
	$(CPPC) $(CFLAGS) -o matmult matmult.c

powermod: powermod.c
	$(CPPC) $(CFLAGS) -o powermod powermod.c

clean:
	rm powermod matmult